# Generated by Django 5.0 on 2024-10-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Publicacion',
        ),
    ]
