# Generated by Django 4.2 on 2024-10-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='foro',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='tematica',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='PalabraProhibida',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Foro',
        ),
        migrations.DeleteModel(
            name='Historial',
        ),
        migrations.DeleteModel(
            name='Tematica',
        ),
    ]
