# Generated by Django 5.0 on 2024-10-19 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foro',
            name='nombre',
            field=models.TextField(max_length=30, unique=True),
        ),
        migrations.RemoveField(
            model_name='foro',
            name='tematicas',
        ),
        migrations.AddField(
            model_name='foro',
            name='tematicas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foros.tematica'),
        ),
    ]
