# Generated by Django 5.0 on 2024-10-19 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0004_alter_foro_nombre_remove_foro_tematicas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foro',
            old_name='tematicas',
            new_name='tematica',
        ),
    ]
