# Generated by Django 5.0 on 2024-10-19 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0005_rename_tematicas_foro_tematica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foro',
            name='tematica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foros.tematica'),
        ),
    ]
